defmodule ResidentialTenancyAct.Repo.Migrations.DefineNswRtaRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :part_id,
             references(:nsw_rta_parts,
               column: :id,
               name: "nsw_rta_sections_part_id_fkey",
               type: :text
             )
    end

    create index(:nsw_rta_sections, [:part_id], prefix: "rtas")

    alter table(:nsw_rta_divisions, prefix: "rtas") do
      add :division_id, :text

      modify :part_id,
             references(:nsw_rta_parts,
               column: :id,
               name: "nsw_rta_divisions_part_id_fkey",
               type: :text
             )
    end

    create index(:nsw_rta_divisions, [:part_id], prefix: "rtas")
  end

  def down do
    drop_if_exists index(:nsw_rta_divisions, [:part_id], prefix: "rtas")

    drop constraint(:nsw_rta_divisions, "nsw_rta_divisions_part_id_fkey", prefix: "rtas")

    alter table(:nsw_rta_divisions, prefix: "rtas") do
      modify :part_id, :text
      remove :division_id
    end

    drop_if_exists index(:nsw_rta_sections, [:part_id], prefix: "rtas")

    drop constraint(:nsw_rta_sections, "nsw_rta_sections_part_id_fkey", prefix: "rtas")

    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :part_id, :text
    end
  end
end
