defmodule ResidentialTenancyAct.Repo.Migrations.AddIndexToEmbeddings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First alter the embeddings column to specify dimensions
    execute """
    ALTER TABLE rtas.nsw_rta_sections
    ALTER COLUMN embeddings TYPE vector(1024)
    """

    # Then create the HNSW index
    execute """
    CREATE INDEX nsw_rta_sections_embeddings_idx ON rtas.nsw_rta_sections
    USING hnsw (embeddings vector_cosine_ops)
    WITH (m = 16, ef_construction = 64)
    """
  end

  def down do
    execute """
    DROP INDEX IF EXISTS rtas.nsw_rta_sections_embeddings_idx
    """

    execute """
    ALTER TABLE rtas.nsw_rta_sections
    ALTER COLUMN embeddings TYPE vector
    """
  end
end
