defmodule ResidentialTenancyAct.Repo.Migrations.AddMessageRelationshipToPromptHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompt_history) do
      modify :message_id,
             references(:messages,
               column: :id,
               name: "prompt_history_message_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:prompt_history, [:message_id])
  end

  def down do
    drop_if_exists index(:prompt_history, [:message_id])

    drop constraint(:prompt_history, "prompt_history_message_id_fkey")

    alter table(:prompt_history) do
      modify :message_id, :uuid
    end
  end
end
