defmodule ResidentialTenancyAct.Repo.Migrations.AddHashAndEmbeddingsStaleFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      add :hash, :text
      add :embeddings_stale, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      remove :embeddings_stale
      remove :hash
    end
  end
end
