defmodule ResidentialTenancyAct.Repo.Migrations.DefineNswRtaSectionRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :division_id,
             references(:nsw_rta_divisions,
               column: :id,
               name: "nsw_rta_sections_division_id_fkey",
               type: :text
             )
    end

    create index(:nsw_rta_sections, [:division_id], prefix: "rtas")
  end

  def down do
    drop_if_exists index(:nsw_rta_sections, [:division_id], prefix: "rtas")

    drop constraint(:nsw_rta_sections, "nsw_rta_sections_division_id_fkey", prefix: "rtas")

    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :division_id, :text
    end
  end
end
