defmodule ResidentialTenancyAct.Repo.Migrations.RemoveCompositeKeyFromNswRtaDivisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("nsw_rta_divisions", "nsw_rta_divisions_pkey", prefix: "rtas")

    alter table(:nsw_rta_divisions, prefix: "rtas") do
      modify :part_id, :text
    end

    execute("ALTER TABLE rtas.nsw_rta_divisions ADD PRIMARY KEY (id)")
  end

  def down do
    alter table(:nsw_rta_divisions, prefix: "rtas") do
      modify :part_id, :text
    end

    execute("ALTER TABLE rtas.nsw_rta_divisions DROP constraint nsw_rta_divisions_pkey")

    execute("ALTER TABLE rtas.nsw_rta_divisions ADD PRIMARY KEY (id, part_id)")
  end
end
