defmodule ResidentialTenancyAct.Repo.Migrations.AddTitleFieldToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :title, :text
    end
  end

  def down do
    alter table(:conversations) do
      remove :title
    end
  end
end
