defmodule ResidentialTenancyAct.Repo.Migrations.AddNswRtaTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS rtas")

    create table(:nsw_rta_sections, primary_key: false, prefix: "rtas") do
      add :section_id, :text, null: false, primary_key: true
      add :section_title, :text, null: false
      add :part_id, :text, null: false
      add :division_id, :text, null: false
      add :text, :text, null: false
      add :embeddings, :vector, null: false
      add :url, :text, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS rtas")

    create table(:nsw_rta_parts, primary_key: false, prefix: "rtas") do
      add :id, :text, null: false, primary_key: true
      add :title, :text, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS rtas")

    create table(:nsw_rta_divisions, primary_key: false, prefix: "rtas") do
      add :id, :text, null: false, primary_key: true
      add :title, :text, null: false
      add :part_id, :text, null: false
    end
  end

  def down do
    drop table(:nsw_rta_divisions, prefix: "rtas")

    drop table(:nsw_rta_parts, prefix: "rtas")

    drop table(:nsw_rta_sections, prefix: "rtas")
  end
end
