defmodule ResidentialTenancyAct.Repo.Migrations.AddPromptHistoryTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_history, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :message_id, :uuid, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "prompt_history_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :content, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:prompt_history, "prompt_history_user_id_fkey")

    drop table(:prompt_history)
  end
end
