defmodule ResidentialTenancyAct.Repo.Migrations.UpdateNswRtaSectionsFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:nsw_rta_sections, prefix: "rtas"), :section_id, to: :id

    rename table(:nsw_rta_sections, prefix: "rtas"), :section_title, to: :title

    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :embeddings, :vector, null: true
      modify :text, :text, null: true
    end
  end

  def down do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      modify :text, :text, null: false
      modify :embeddings, :vector, null: false
    end

    rename table(:nsw_rta_sections, prefix: "rtas"), :title, to: :section_title

    rename table(:nsw_rta_sections, prefix: "rtas"), :id, to: :section_id
  end
end
