defmodule ResidentialTenancyAct.Repo.Migrations.AddTokenCountField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      add :token_count, :bigint
    end
  end

  def down do
    alter table(:nsw_rta_sections, prefix: "rtas") do
      remove :token_count
    end
  end
end
